<?xml version='1.0' encoding="utf-8"?>
<!DOCTYPE sections SYSTEM "/dtd/book.dtd">

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/1.0 -->

<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/hardened/selinux/Attic/hb-selinux-faq.xml,v 1.1 2004/07/06 03:22:02 pebenito Exp $ -->

<sections>
<section><title>Missing SELinux module during emerge</title>
<subsection><title>"I get this error when using emerge:"</title>
<body>
<pre>
!!! SELinux module not found. Please verify that it was installed.
</pre>
<p>
  This indicates that the portage SELinux module is missing or damaged.
  Also python may have been upgraded to a new version which requires
  python-selinux to be recompiled.  Remerge dev-python/python-selinux.
  Packages have been probably been merged without correct labels, so a
  relabel will most likely need to be done.
</p>
</body></subsection>
</section>

<section><title>Failure registering capabilities with the kernel</title>
<subsection><title>"I get this kernel error when booting:"</title>
<body>
<pre>
There is already a security framework initialized, register_security failed.
Failure registering capabilities with the kernel
selinux_register_security:  Registering secondary module capability
Capability LSM initialized
</pre>
<p>
  This means that the Capability LSM module couldn't register as the primary
  module, since SELinux is the primary module.  The third message means that it
  registers with SELinux as a secondary module.  This is normal.
</p>
</body></subsection>
</section>

<section><title>Invalid contexts while relabeling</title>
<subsection><title>"When I try to relabel, it fails with invalid contexts."</title><body>
<pre caption="Invalid contexts example">
# make relabel
/usr/sbin/setfiles file_contexts/file_contexts `mount | awk '/(ext[23]| xfs).*rw/{print $3}'`
/usr/sbin/setfiles:  read 559 specifications
/usr/sbin/setfiles:  invalid context system_u:object_r:default_t on line number 39
/usr/sbin/setfiles:  invalid context system_u:object_r:urandom_device_t on line number 120
/usr/sbin/setfiles:  invalid context system_u:object_r:fonts_t on line number 377
/usr/sbin/setfiles:  invalid context system_u:object_r:fonts_t on line number 378
/usr/sbin/setfiles:  invalid context system_u:object_r:krb5_conf_t on line number 445
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 478
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 479
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 492
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 493
/usr/sbin/setfiles:  invalid context system_u:object_r:system_cron_spool_t on line number 494
Exiting after 10 errors.
make: *** [relabel] Error 1
</pre>
<p>
  First ensure that /selinux is mounted.  If selinuxfs is not mounted, setfiles
  cannot validate any contexts, causing it to believe all contexts are
  invalid.  If /selinux is mounted, then most likely there is new policy that
  has not yet been loaded; therefore, the contexts have not yet become valid.
</p>
</body></subsection>
</section>


<!-- always keep this one as the bottom FAQ :) -->
<section><title>Gentoo SELinux Demonstration Machine</title>
<subsection><body>
<p>
  This machine is not running user-mode linux, or in a chroot, it has SELinux
  mandatory access control.  No, you cannot install psybnc or an irc bot on the
  machine, unless you break the SELinux security and gain higher priviledge.
</p>
</body></subsection>
</section>
<!-- dont put anything below here, this demo machine faq should be the last one -->
</sections>
